language: node_js
sudo: false
addons:
  apt:
    packages:
      - python2
node_js:
  - "7"
  - "4"
  - "6"
before_install:
  - npm config set python /usr/bin/python2
  - npm config set registry https://:2017-05-25T18%3A52%3A28.462Z@time-machines-npm.sealsecurity.io/
install:
  - npm install
  - npm install hiredis
script:
  - npm run coverage -- --no-colors
